# Generated by Django 2.2.10 on 2020-07-24 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_auto_20181115_1953'),
    ]

    # The parallel stock-integrity migration (0002_stock_integrity) already
    # copies the legacy price fields, renames the selling price, and removes
    # these columns. Keep this historical node as a no-op so the merged graph
    # does not apply the same field changes twice.
    operations = []
