# Generated by Django 6.0.6 on 2026-10-03 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0008_merge_stock_integrity_partneraddress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockrecord',
            options={},
        ),
        migrations.RenameIndex(
            model_name='stockrecord',
            new_name='partner_sto_product_e2b97c_idx',
            old_name='partner_stock_product_idx',
        ),
        migrations.RenameIndex(
            model_name='stockrecord',
            new_name='partner_sto_partner_3c83ff_idx',
            old_name='partner_stock_updated_idx',
        ),
        migrations.AlterUniqueTogether(
            name='stockrecord',
            unique_together=set(),
        ),
    ]
