# Generated by Django 6.1.1 on 2026-09-29 07:30

import apps.mis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0002_purchase_status_possale_possaleitem_purchaseitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='currency',
            field=models.CharField(default=apps.mis.models.default_store_currency, max_length=12),
        ),
    ]
