# Generated by Django 6.0.6 on 2026-09-30

from django.conf import settings
from django.db import migrations, models
from django.db.models import Q
import django.core.validators
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("mis", "0003_payment_transaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="CashierShift",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("opened_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("opening_cash", models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ("expected_cash", models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ("closing_cash", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ("cash_difference", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("status", models.CharField(choices=[("open", "Open"), ("closed", "Closed")], db_index=True, default="open", max_length=10)),
                ("note", models.CharField(blank=True, max_length=240)),
                ("cashier", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cashier_shifts", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-opened_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="cashiershift",
            index=models.Index(fields=["cashier", "status"], name="mis_shift_cashier_status_idx"),
        ),
        migrations.AddIndex(
            model_name="cashiershift",
            index=models.Index(fields=["opened_at", "status"], name="mis_shift_opened_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="cashiershift",
            constraint=models.CheckConstraint(condition=Q(("opening_cash__gte", 0)), name="mis_shift_opening_nonnegative"),
        ),
        migrations.AddConstraint(
            model_name="cashiershift",
            constraint=models.CheckConstraint(condition=Q(("expected_cash__gte", 0)), name="mis_shift_expected_nonnegative"),
        ),
        migrations.AddConstraint(
            model_name="cashiershift",
            constraint=models.CheckConstraint(condition=Q(("closing_cash__gte", 0)) | Q(("closing_cash__isnull", True)), name="mis_shift_closing_nonnegative"),
        ),
    ]
