# Generated by Django 6.1.1 on 2026-09-29 07:32

from django.db import migrations, models


def normalize_old_expense_categories(apps, schema_editor):
    Expense = apps.get_model("mis", "Expense")
    Expense.objects.filter(category="operations").update(category="maintenance")
    Expense.objects.filter(category="delivery").update(category="transportation")
    Expense.objects.filter(category="marketing").update(category="other")


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0003_purchase_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank transfer'), ('other', 'Other')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('electricity', 'Electricity'), ('rent', 'Rent'), ('salary', 'Salary'), ('transportation', 'Transportation'), ('internet', 'Internet'), ('maintenance', 'Maintenance'), ('other', 'Other')], max_length=20),
        ),
        migrations.RunPython(normalize_old_expense_categories, migrations.RunPython.noop),
    ]
