# Generated by Django 6.0.6 on 2026-10-03 08:09

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0032_category_exclude_from_menu_category_long_description'),
        ('mis', '0011_possale_customer_contact'),
        ('partner', '0009_alter_stockrecord_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cashiershift',
            new_name='mis_cashier_cashier_66b25f_idx',
            old_name='mis_shift_cashier_status_idx',
        ),
        migrations.RenameIndex(
            model_name='cashiershift',
            new_name='mis_cashier_opened__42e50d_idx',
            old_name='mis_shift_opened_status_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='mis_expense_categor_901c3d_idx',
            old_name='mis_expense_cat_spent_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='mis_expense_payment_d110fd_idx',
            old_name='mis_expense_pay_spent_idx',
        ),
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='mis_payment_status_6d3324_idx',
            old_name='mis_payment_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='mis_payment_method_a9740f_idx',
            old_name='mis_payment_method_created_idx',
        ),
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='mis_payment_sale_id_742700_idx',
            old_name='mis_payment_sale_created_idx',
        ),
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='mis_payment_order_i_fe25b0_idx',
            old_name='mis_payment_order_created_idx',
        ),
        migrations.RenameIndex(
            model_name='purchase',
            new_name='mis_purchas_supplie_9e3f19_idx',
            old_name='mis_purchase_supplier_date_idx',
        ),
        migrations.RenameIndex(
            model_name='purchase',
            new_name='mis_purchas_status_360197_idx',
            old_name='mis_purchase_status_date_idx',
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='possale',
            name='amount_tendered',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='possale',
            name='change_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='possale',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='possale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank transfer'), ('split', 'Split payment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='possale',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='possale',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='possale',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='possaleitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='possaleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='possaleitem',
            name='unit_tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='possalereturn',
            name='refund_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank transfer'), ('split', 'Split payment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='possalereturn',
            name='refund_total',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='possalereturnitem',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddIndex(
            model_name='possale',
            index=models.Index(fields=['created_at', 'payment_method'], name='mis_possale_created_11809a_idx'),
        ),
        migrations.AddIndex(
            model_name='possale',
            index=models.Index(fields=['customer', 'created_at'], name='mis_possale_custome_36be7d_idx'),
        ),
        migrations.AddIndex(
            model_name='possaleitem',
            index=models.Index(fields=['sale', 'product'], name='mis_possale_sale_id_9bf158_idx'),
        ),
        migrations.AddIndex(
            model_name='possaleitem',
            index=models.Index(fields=['stockrecord'], name='mis_possale_stockre_0f7b8a_idx'),
        ),
        migrations.AddIndex(
            model_name='possalereturn',
            index=models.Index(fields=['sale', 'created_at'], name='mis_possale_sale_id_25acb8_idx'),
        ),
        migrations.AddIndex(
            model_name='possalereturn',
            index=models.Index(fields=['refund_method', 'created_at'], name='mis_possale_refund__a3872d_idx'),
        ),
        migrations.AddIndex(
            model_name='possalereturnitem',
            index=models.Index(fields=['sale_return', 'sale_item'], name='mis_possale_sale_re_9c7755_idx'),
        ),
        migrations.AddIndex(
            model_name='possalereturnitem',
            index=models.Index(fields=['sale_item'], name='mis_possale_sale_it_651c82_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseitem',
            index=models.Index(fields=['purchase', 'product'], name='mis_purchas_purchas_57f8aa_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseitem',
            index=models.Index(fields=['stockrecord'], name='mis_purchas_stockre_38dff0_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', 'created_at'], name='mis_stockmo_movemen_d7540f_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reference', 'created_at'], name='mis_stockmo_referen_6af927_idx'),
        ),
    ]
