import { useEffect,useState } from 'react'
import { Navigate } from 'react-router-dom'
import { apiRequest } from '../services/api'
import { useAuth } from '../context/AuthContext'

const initial={category:'electricity',description:'',amount:'',payment_method:'cash',spent_at:new Date().toISOString().slice(0,10),notes:''}
export default function ExpensesPage(){
 const {user,ready}=useAuth();const [expenses,setExpenses]=useState([]);const [form,setForm]=useState(initial);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [currency,setCurrency]=useState('AFN')
 async function reload(){try{const data=await apiRequest('/expenses/');setExpenses(data.results||data)}catch(err){setError(err.message)}}
 useEffect(()=>{if(user?.is_staff){reload();apiRequest('/config/').then(config=>setCurrency(config.currency)).catch(()=>{})}},[user])
 if(!ready)return <section className="site-container page-section"><div className="product-skeleton detail-skeleton"/></section>
 if(!user)return <Navigate to="/login" replace/>
 if(!user.is_staff)return <section className="site-container page-section"><div className="state-card"><strong>Staff access required.</strong></div></section>
 async function save(event){event.preventDefault();setBusy(true);setError('');try{await apiRequest('/expenses/',{method:'POST',body:JSON.stringify({...form,amount:Number(form.amount)})});setForm({...initial,spent_at:new Date().toISOString().slice(0,10)});await reload()}catch(err){setError(err.data&&typeof err.data==='object'?Object.values(err.data).flat().join(' '):err.message)}finally{setBusy(false)}}
 const money=amount=>new Intl.NumberFormat(undefined,{style:'currency',currency}).format(amount||0)
 return <section className="site-container page-section"><div className="page-title-row"><div><span className="eyebrow">FINANCIAL MANAGEMENT</span><h1>Expenses</h1><p>Record operating costs with date and payment method.</p></div></div>{error&&<div className="inline-error" role="alert">{error}</div>}<div className="inventory-grid"><article className="dashboard-panel"><h2>Record expense</h2><form className="staff-form" onSubmit={save}><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{[['electricity','Electricity'],['rent','Rent'],['salary','Salary'],['transportation','Transportation'],['internet','Internet'],['maintenance','Maintenance'],['other','Other']].map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>Description<input required maxLength="240" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Amount<input required type="number" min="0.01" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Date<input required type="date" value={form.spent_at} onChange={e=>setForm({...form,spent_at:e.target.value})}/></label><label>Payment method<select value={form.payment_method} onChange={e=>setForm({...form,payment_method:e.target.value})}><option value="cash">Cash</option><option value="card">Card</option><option value="bank_transfer">Bank transfer</option><option value="other">Other</option></select></label><label>Notes<input value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button className="button-primary" disabled={busy}>{busy?'Saving…':'Save expense'}</button></form></article><article className="dashboard-panel"><h2>Recent expenses</h2>{expenses.length===0?<p className="muted-empty">No expenses recorded.</p>:expenses.map(e=><div className="dashboard-row" key={e.id}><span><strong>{e.description}</strong><br/>{e.category} · {e.payment_method} · {e.spent_at}</span><b>{money(e.amount)}</b></div>)}</article></div></section>
}
