import { useState } from 'react'
import { Navigate } from 'react-router-dom'
import { RotateCcw, Search } from 'lucide-react'
import { useAuth } from '../context/AuthContext'
import { api, apiRequest } from '../services/api'

export default function POSReturnsPage(){
 const {user,ready}=useAuth();const [invoice,setInvoice]=useState('');const [sale,setSale]=useState(null);const [quantities,setQuantities]=useState({});const [reason,setReason]=useState('');const [method,setMethod]=useState('cash');const [restock,setRestock]=useState(true);const [error,setError]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false)
 if(!ready)return <section className="site-container page-section"><div className="product-skeleton detail-skeleton"/></section>
 if(!user)return <Navigate to="/login" replace/>
 if(!user.is_staff)return <section className="site-container page-section"><div className="state-card"><strong>Staff access required.</strong></div></section>
 const currency=sale?.currency||'AFN';const money=value=>new Intl.NumberFormat(undefined,{style:'currency',currency}).format(value||0)
 async function findSale(event){event.preventDefault();setError('');setMessage('');try{const result=await api.posSaleDetail(invoice.trim());setSale(result);setQuantities({})}catch(err){setSale(null);setError(err.message)}}
 const refund=sale?sale.items.reduce((sum,item)=>sum+(Number(item.unit_price)+Number(item.unit_tax))*Number(quantities[item.id]||0),0):0
 async function submit(event){event.preventDefault();setBusy(true);setError('');setMessage('');try{const items=sale.items.filter(item=>Number(quantities[item.id])>0).map(item=>({sale_item_id:item.id,quantity:Number(quantities[item.id])}));const result=await apiRequest(`/pos/sales/${encodeURIComponent(sale.invoice_number)}/returns/`,{method:'POST',body:JSON.stringify({items,refund_method:method,reason,restocked:restock})});setMessage(`Return ${result.invoice_number} recorded. Refund: ${money(result.refund_total)}.`);setSale(await api.posSaleDetail(sale.invoice_number));setQuantities({})}catch(err){setError(err.data&&typeof err.data==='object'?Object.values(err.data).flat().join(' '):err.message)}finally{setBusy(false)}}
 return <section className="site-container page-section"><div className="page-title-row"><div><span className="eyebrow">POS RETURNS</span><h1>Process a return</h1><p>Find the original invoice, choose quantities, and record the refund and restock decision.</p></div></div>{error&&<div className="inline-error" role="alert">{error}</div>}{message&&<div className="form-message">{message}</div>}
   <form className="return-search" onSubmit={findSale}><label>POS invoice number<input required value={invoice} onChange={e=>setInvoice(e.target.value)} placeholder="POS-YYYYMMDD-…"/></label><button className="button-primary"><Search size={16}/> Find sale</button></form>
   {sale&&<form className="return-form" onSubmit={submit}><article className="dashboard-panel"><h2>{sale.invoice_number} · {new Date(sale.created_at).toLocaleString()}</h2><div className="orders-table-wrap"><table className="orders-table"><thead><tr><th>Product</th><th>Sold</th><th>Returned</th><th>Unit incl. tax</th><th>Return qty</th></tr></thead><tbody>{sale.items.map(item=><tr key={item.id}><td>{item.title}</td><td>{item.quantity}</td><td>{item.returned_quantity}</td><td>{money(Number(item.unit_price)+Number(item.unit_tax))}</td><td><input aria-label={`Return quantity for ${item.title}`} type="number" min="0" max={item.returnable_quantity} value={quantities[item.id]||''} disabled={!item.returnable_quantity} onChange={e=>setQuantities({...quantities,[item.id]:e.target.value})}/></td></tr>)}</tbody></table></div></article>
    <article className="dashboard-panel return-options"><label>Reason<input required maxLength="240" value={reason} onChange={e=>setReason(e.target.value)}/></label><label>Refund method<select value={method} onChange={e=>setMethod(e.target.value)}><option value="cash">Cash</option><option value="card">Card</option><option value="bank_transfer">Bank transfer</option></select></label><label className="restock-choice"><input type="checkbox" checked={restock} onChange={e=>setRestock(e.target.checked)}/> Items are in resale condition; return them to stock</label><div className="purchase-total"><span>Refund calculated by server</span><strong>{money(refund)}</strong></div><button className="button-primary" disabled={busy||refund<=0}><RotateCcw size={16}/>{busy?'Recording return…':'Record refund and return'}</button></article></form>}
 </section>
}
