import { useEffect, useState } from 'react'
import { Navigate } from 'react-router-dom'
import { Plus, Search, Trash2 } from 'lucide-react'
import { api, apiRequest } from '../services/api'
import { useAuth } from '../context/AuthContext'

export default function PurchasesPage(){
  const {user,ready}=useAuth();const [suppliers,setSuppliers]=useState([]);const [purchases,setPurchases]=useState([]);const [query,setQuery]=useState('');const [matches,setMatches]=useState([]);const [items,setItems]=useState([]);const [supplier,setSupplier]=useState('');const [reference,setReference]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false)
  async function reload(){try{const [s,p]=await Promise.all([apiRequest('/suppliers/'),apiRequest('/purchases/')]);setSuppliers(s.results||s);setPurchases(p.results||p)}catch(err){setError(err.message)}}
  useEffect(()=>{if(user?.is_staff)reload()},[user])
  useEffect(()=>{const timer=setTimeout(()=>{if(query.trim())api.posSearch(query.trim()).then(data=>setMatches(data.results||[])).catch(err=>setError(err.message));else setMatches([])},180);return()=>clearTimeout(timer)},[query])
  if(!ready)return <section className="site-container page-section"><div className="product-skeleton detail-skeleton"/></section>
  if(!user)return <Navigate to="/login" replace/>
  if(!user.is_staff)return <section className="site-container page-section"><div className="state-card"><strong>Staff access required.</strong></div></section>
  function add(product){setItems(old=>old.some(i=>i.id===product.id)?old: [...old,{id:product.id,title:product.title,barcode:product.upc,currency:product.currency,quantity:1,unit_cost:product.price||'0.00'}]);setQuery('');setMatches([])}
  const total=items.reduce((sum,item)=>sum+Number(item.unit_cost||0)*Number(item.quantity||0),0)
  async function receive(event){event.preventDefault();setBusy(true);setError('');try{await apiRequest('/purchases/receive/',{method:'POST',body:JSON.stringify({supplier_id:supplier,reference,purchased_at:new Date().toISOString().slice(0,10),items:items.map(i=>({product_id:i.id,quantity:Number(i.quantity),unit_cost:i.unit_cost}))})});setItems([]);setReference('');await reload()}catch(err){setError(err.data&&typeof err.data==='object'?Object.values(err.data).flat().join(' '):err.message)}finally{setBusy(false)}}
  const money=n=>new Intl.NumberFormat(undefined,{style:'currency',currency:items[0]?.currency||'AFN'}).format(n||0)
  return <section className="site-container page-section"><div className="page-title-row"><div><span className="eyebrow">PURCHASES & RECEIVING</span><h1>Purchases</h1><p>Record a supplier delivery and increase stock with an audit trail.</p></div></div>{error&&<div className="inline-error" role="alert">{error}</div>}
    <div className="inventory-grid"><article className="dashboard-panel"><h2>Receive a purchase</h2><form className="staff-form" onSubmit={receive}><label>Supplier<select required value={supplier} onChange={e=>setSupplier(e.target.value)}><option value="">Choose supplier</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Supplier invoice reference<input required maxLength="80" value={reference} onChange={e=>setReference(e.target.value)}/></label><label className="purchase-search"><span>Find product by name or barcode</span><div><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search catalogue"/></div>{matches.length>0&&<div className="purchase-matches">{matches.map(p=><button type="button" key={p.id} onClick={()=>add(p)}><span>{p.title}<small>{p.upc||'No barcode'}</small></span><Plus size={15}/></button>)}</div>}</label><div className="purchase-lines">{items.map((item,index)=><div className="purchase-line" key={item.id}><span>{item.title}<small>{item.barcode}</small></span><input aria-label="Quantity" min="1" type="number" value={item.quantity} onChange={e=>setItems(old=>old.map((row,i)=>i===index?{...row,quantity:e.target.value}:row))}/><input aria-label="Unit cost" min="0" step="0.01" type="number" value={item.unit_cost} onChange={e=>setItems(old=>old.map((row,i)=>i===index?{...row,unit_cost:e.target.value}:row))}/><button type="button" className="icon-button danger-icon" aria-label="Remove item" onClick={()=>setItems(old=>old.filter((_,i)=>i!==index))}><Trash2 size={15}/></button></div>)}</div><div className="purchase-total"><span>Purchase total</span><strong>{money(total)}</strong></div><button className="button-primary" disabled={busy||items.length===0||suppliers.length===0}>{busy?'Recording receipt…':'Receive purchase'}</button></form></article>
      <article className="dashboard-panel"><h2>Recent purchases</h2>{purchases.length===0?<p className="muted-empty">No purchases recorded.</p>:purchases.map(p=><div className="dashboard-row" key={p.id}><span><strong>{p.reference}</strong><br/>{p.supplier_name} · {p.item_count} lines · {p.purchased_at}</span><b>{money(p.total_cost)}</b></div>)}</article></div>
  </section>
}
